# Generated by Django 2.1.7 on 2021-02-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
