# Generated by Django 3.1.7 on 2021-05-27 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_auto_20210527_0940'),
        ('seller', '0004_auto_20210526_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
