# Generated by Django 3.1.7 on 2021-05-27 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
    ]
