# Generated by Django 3.1.7 on 2021-05-26 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EcommerceProject', '0003_auto_20210211_1426'),
        ('buyer', '0003_auto_20210511_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='User',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='amt_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('UnPaid', 'UnPaid')], default='UnPaid', max_length=20),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order_id',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='placed_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EcommerceProject.userprofile'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='total_amt',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='processing', max_length=50),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
