# Generated by Django 3.1.7 on 2021-06-07 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='User',
        ),
    ]
