# Generated by Django 3.1.7 on 2021-06-07 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0009_remove_orderproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='buyer.address'),
        ),
    ]
