# Generated by Django 2.1.7 on 2021-02-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceProject', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
